CREATE TABLE greenhouse_plants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    family TEXT,
    watered TIMESTAMP DEFAULT now(),
    notes TEXT,
    image TEXT,
    user_id INTEGER
        REFERENCES greenhouse_users(id) ON DELETE CASCADE NOT NULL
);
